### PR TITLE
Fixup setup so that it works without extra mucking around

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by martinthomson** [comment]
Sorry, messed up the last one somehow.

**Comment by martinthomson** [comment]
BTW, you shouldn't have to copy the dtd and entity files in.  That should be done by the makefile, or better yet, they should point to files in the support structure.

**Comment by reschke** [comment]
What's the "support structure"? "/lib"?

**Comment by martinthomson** [comment]
If the dtd and xslt files can be coped in from `/lib` or `/lib/rfc2629xslt` or somewhere else, that's best.  You should then add them to the `.gitignore` if you do that too.  It just reduces the amount of stuff that someone needs to keep in their repo in order to have it be usable.

**Comment by reschke** [comment]
Well, the placement of thee DTD files is caused by kramdown-rfc2629... Is that configurable somehow? Or can it be told not to reference a DTD?

**Comment by martinthomson** [comment]
That's odd, because I use kramdown-rfc2629 and I've never seen those files created.  I thought that you added them for your xslt processing stuff.

**Comment by reschke** [comment]
They aren't created, but they are _referenced_. Once they are referenced you need them to parse as XML.

**Comment by martinthomson** [comment]
Ugh, does that mean that `xml2rfc` is being unusually tolerant when it permits them to be absent?  It's fairly easy to ensure that they are installed: find a place that they live, make a rule that copies them into place, make their new location a dependency of the rules that depend on them being present.

**Comment by reschke** [comment]
xml2rfc has some extra magic to validate against it's own copy of the DTD, but that's not something to rely on with other XML tools.

I guess the best fix is to either tell kramdown to omit the DTD declaration, or the ability to state where it is.

We could also just remove the DTD declaration; but I'm not sure whether kramdown ocasionally generates content that requires it (wrt entity declarations)

**Comment by martinthomson** [comment]
I doubt that they actually use the DTD, it's probably safe to excise.

**Comment by reschke** [comment]
if we know that it's not needed then we can also run xsltproc in a non-DTD-reading mode. Let me try that.

**Comment by reschke** [comment]
-> https://github.com/reschke/i-d-template/commit/0c983d139d4fff05e9a02831d7980992b673e80c

**Pull request merged**
